version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      # step1: obtain repo from github
      - checkout
      # step2: create virtualenv and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: run tests
          command:
            . venv/bin/activate
            flake8 --exclude=venv* --statistics
            pytest -v --cov=my_func
