version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      # step1: obtain repo from github
      - checkout
      # step2: create virtualenv and install dependencies
      - run:
          name: install dependencies
          command: |
            virtualenv -p /usr/local/bin/python3.7 .env
            source .env/bin/activate
            pip install -r requirements.txt

      - run:
          name: run tests
          command: |
            source .env/bin/activate
            flake8 --exclude=venv* --statistics
            python -m pytest -v --cov=my_func
